

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class SignUpUI : MonoBehaviour
{
    public TMP_InputField emailInput;
    public TMP_InputField passwordInput;
    public TMP_InputField nameInput;
    public TMP_Text errorText;
    public Button signUpButton;
    public Button cancelButton;

    public GameObject SignInUI;
    public GameObject profileUI;

    void Init()
    {
        signUpButton.onClick.AddListener(SignUp);
        cancelButton.onClick.AddListener(Cancel);
    }

     bool Validate()
    {
        if (string.IsNullOrWhiteSpace(emailInput.text))
        {
            errorText.text = "ï¿½Ì¸ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ô·ï¿½ï¿½ï¿½ ï¿½Ö¼ï¿½ï¿½ï¿½";
            return false;
        }
        if (string.IsNullOrWhiteSpace(passwordInput.text))
        {
            errorText.text = "ï¿½ï¿½Ð¹ï¿½È£ï¿½ï¿? ï¿½Ô·ï¿½ï¿½ï¿½ ï¿½Ö¼ï¿½ï¿½ï¿½";
        }
        if (passwordInput.text.Length < 6)
        {
            errorText.text = "ï¿½ï¿½Ð¹ï¿½È£ï¿½ï¿? 6ï¿½Ú¸ï¿½ ï¿½Ì»ï¿½ï¿½Ì¾ï¿½ï¿? ï¿½Õ´Ï´ï¿½";
            return false;
        }
        if (string.IsNullOrWhiteSpace(nameInput.text))
        {
            errorText.text = "ï¿½Ì¸ï¿½ï¿½ï¿½ ï¿½Ô·ï¿½ï¿½ï¿½ ï¿½Ö¼ï¿½ï¿½ï¿½";
            return false;
        }
        
        return true;
    }

    void SetInteractable(bool interactable)
    {
        emailInput.interactable = interactable;
        passwordInput.interactable = interactable;
        nameInput.interactable = interactable;
        signUpButton.interactable = interactable;
        cancelButton.interactable = interactable;
    }

    void SignUp()
    {
        if (Validate())
        {
            SetInteractable(false);
            AuthManager.Instance.SignUp(emailInput.text, passwordInput.text, nameInput.text, SignUpCallback);
        }
    }

    void SignUpCallback(AuthManager.SignUpError error)
    {
        if (error == AuthManager.SignUpError.None)
        {
            //ï¿½Î±ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½
            gameObject.SetActive(false);
            //profileUI.SetActive(true);
            SignInUI.SetActive(true);
            
        }
        else
        {
            errorText.text = error switch
            {
                AuthManager.SignUpError.InvalidEmail => "ï¿½Ì¸ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ã¹Ù¸ï¿½ï¿½ï¿½ ï¿½Ê½ï¿½ï¿½Ï´ï¿½",
                AuthManager.SignUpError.EmailAlreadyInUse => "ï¿½Ì¹ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿? ï¿½Ì¸ï¿½ï¿½ï¿½ ï¿½Ô´Ï´ï¿½",
                _ => "ï¿½ï¿½Æ®ï¿½ï¿½Å© ï¿½ï¿½ï¿½ï¿½"
            };
        }
        SetInteractable(true);
    }

    void Cancel()
    {
        gameObject.SetActive(false);
        SignInUI.SetActive(true);
    }

    // Start is called before the first frame update
    void Start()
    {
        Init();
    }

    private void OnEnable()
    {
        emailInput.text = null;
        passwordInput.text = null;
        nameInput.text = null;
        errorText.text = null;
    }
}
